#!/bin/bash
#
# This script configures a fresh install of Ubuntu Server to my liking. 
# Script assumes a base install only (no SSH, etc) are installed when the
#   system is set up.

# Script Variables (Default values)

default=Y                 #Default reply value; Leave Y
git_user=taxbender        #Github username
git_email=email           #Github user email



# Add repos



# Update Repos / Upgrade System

sudo apt-get -y --force-yes update
sudo apt-get -y --force-yes upgrade

# Install applications

sudo apt-get -y install \
  openssh-server
  git-core
  
# Configure git
git config --global user.name "$git_user"
git config --global user.email "$git_email"


  
clear
echo "Default applications installed"
echo ""
echo ""
  
# Option to install virtual desktop
read -p "Do you want to install vnc virtual deskptop? [$default / n] " reply

reply=${reply: -$default}


if [ $reply = y|Y ]
  then
    sudo apt-get install \
      gnome-core \
      gnome-session-fallback \
      vnc4server
      
    
    
  else
    echo ""
    echo "Virtual desktop not installed."
    echo ""
fi
