#!/bin/bash
#
# This script configures a fresh install of Ubuntu Server to my liking. 
#   Assumes a base install with ssh-server installed when the
#   system is set up.
#
# Version 0.1
#

# Script Variables (Default values)

default=Y                 #Default reply value; Leave Y
git_user=taxbender        #Github username
git_email=email           #Github user email

# Add repos

# Update Repos / Upgrade System

sudo apt-get -y --force-yes update
sudo apt-get -y --force-yes upgrade

# Install applications

sudo apt-get -y install git-core
  
# Configure git
git config --global user.name "$git_user"
git config --global user.email "$git_email"


# Create new ssh key for Git, using the provided email as a label
ssh-keygen -t rsa -C "Git_sshKey"

echo 

clear
echo "Default applications installed"
echo ""
echo ""
  
# Option to install virtual desktop
read -p "Do you want to install vnc virtual deskptop? [$default / n] " reply

reply=${reply: -$default}

if [ $reply = y|Y ]
  then
    sudo apt-get install \
      gnome-core \
      gnome-session-fallback \
      vnc4server
    
    cat > /home/$USER/.vnc/xstartup <<EOL
    line 1, #!/bin/sh
    line 2, 
    line 3, # Uncomment the following two lines for normal desktop:
    line 4, unset SESSION_MANAGER
    line 5, #exec /etc/X11/xinit/xinitrc
    line 6, gnome-session --session=gnome-classic &
    line 7, 
    line 8, [ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
    line 9, [ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
    line 10, xsetroot -solid grey
    line 11, vncconfig -iconic &
    line 12, #x-terminal-emulator -geometry 1280x1024+10+10 -ls -title "$VNCDESKTOP Desktop" &
    line 13, #x-window-manager &
    EOL
    
    
  else
    echo ""
    echo "Virtual desktop not installed."
    echo ""
fi
